service: myFirstServerlessProject

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
    PENDING_ORDER_QUEUE:
      Ref: PendingOrdersQueue
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource:
        - "arn:aws:sqs:${self:provider.region}:*:PendingOrdersQueue"

functions:
  makeAnOrder:
    handler: pizza.makeAnOrder
    events:
      - http:
          method: post
          path: /make-order

resources:
  Resources:
    PendingOrdersQueue:
      Type: "AWS::SQS::Queue"
      Properties:
          QueueName: "PendingOrdersQueue"
